apiVersion: apps/v1
kind: Deployment
metadata:
  name: avialog
  labels:
    app: avialog
spec:
  replicas: 4
  selector:
    matchLabels:
      app: avialog
  template:
    metadata:
      labels:
        app: avialog
    spec:
      containers:
        - name: avialog
          image: ghcr.io/avialog/backend:30cb310 #docker yaml pushuje obraz do resejtru na github do github register ghcr
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: avialog
                  key: dsn
            - name: FIREBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: avialog
                  key: firebaseKey
            - name: GIN_MODE
              value: release
---
apiVersion: v1
kind: Service
metadata:
  name: avialog
spec:
  selector:
    app: avialog
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avialog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: avialog.enteam.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avialog
                port:
                  number: 3000
